// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWXrgjVJIyUKz2DGpKjd4vdIU7SdwJHMs',
    appId: '1:395577249681:web:1a160095fa703314abd430',
    messagingSenderId: '395577249681',
    projectId: 'smart-buoy-system-d96cb',
    authDomain: 'smart-buoy-system-d96cb.firebaseapp.com',
    databaseURL: 'https://smart-buoy-system-d96cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-buoy-system-d96cb.firebasestorage.app',
    measurementId: 'G-QG00343NYL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy083Bq0eKA4lJuGMFdpBpk3QCEA-Bn4Y',
    appId: '1:395577249681:ios:632bcc96e9a18cecabd430',
    messagingSenderId: '395577249681',
    projectId: 'smart-buoy-system-d96cb',
    databaseURL: 'https://smart-buoy-system-d96cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-buoy-system-d96cb.firebasestorage.app',
    androidClientId: '395577249681-ttoism4t1qir995ro7iimrf3ocksmshc.apps.googleusercontent.com',
    iosClientId: '395577249681-rfg5im8d6o78510esjcnc2vfp7pstmhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquasenseproject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy083Bq0eKA4lJuGMFdpBpk3QCEA-Bn4Y',
    appId: '1:395577249681:ios:632bcc96e9a18cecabd430',
    messagingSenderId: '395577249681',
    projectId: 'smart-buoy-system-d96cb',
    databaseURL: 'https://smart-buoy-system-d96cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-buoy-system-d96cb.firebasestorage.app',
    androidClientId: '395577249681-ttoism4t1qir995ro7iimrf3ocksmshc.apps.googleusercontent.com',
    iosClientId: '395577249681-rfg5im8d6o78510esjcnc2vfp7pstmhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquasenseproject',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClKqBS349OqgpDq-TpD27DKnIBwOsNIx8',
    appId: '1:395577249681:android:76b48fbd959a1dffabd430',
    messagingSenderId: '395577249681',
    projectId: 'smart-buoy-system-d96cb',
    databaseURL: 'https://smart-buoy-system-d96cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-buoy-system-d96cb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWXrgjVJIyUKz2DGpKjd4vdIU7SdwJHMs',
    appId: '1:395577249681:web:961f49058a283022abd430',
    messagingSenderId: '395577249681',
    projectId: 'smart-buoy-system-d96cb',
    authDomain: 'smart-buoy-system-d96cb.firebaseapp.com',
    databaseURL: 'https://smart-buoy-system-d96cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-buoy-system-d96cb.firebasestorage.app',
    measurementId: 'G-2ZPPFN85D7',
  );

}